spring:
  application:
    name: SellerScope
  datasource:
    hikari:
      max-lifetime: 60000
      connection-timeout: 30000
      minimum-idle: 2
      maximum-pool-size: 10
    url: jdbc:postgresql://${DB_HOST}/sellerscope
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  redis:
    host: redis
    port: 6379
    password: ${REDIS_PASSWORD}

  redisson:
    config:
      singleServerConfig:
        address: "redis://redis:6379"
        password: "${REDIS_PASSWORD}"

jwt:
  secret: ${JWT_SECRET}
  access:
    expiration: ${JWT_ACCESS_EXPIRATION}
  refresh:
    expiration: ${JWT_REFRESH_EXPIRATION}

server:
  ssl:
    key-store: ${KEYSTORE_PATH}
    key-store-password: ${KEYSTORE_PASSWORD}
    key-store-type: PKCS12
    key-alias: ${KEYSTORE_ALIAS}
    enabled: true
  port: 443